name: Tests

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      dotnet-version: '5.0.x'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
